### PR TITLE
Update stack

### PR DESCRIPTION
**Pull request by cekees**
This is to get #845 ready to go into master. Update the stack module and has changes form master merged in.

### CODE REVIEW

**Comment by cekees** [comment]
[gw0] [ 16%] FAILED proteus/tests/test_gmsh_generation.py::TestGMSH::test_gmsh_generation_2D 
[gw0] [ 16%] FAILED proteus/tests/test_gmsh_generation.py::TestGMSH::test_gmsh_generation_3D 
[gw0] [ 37%] FAILED proteus/tests/AddedMass/test_addedmass2D.py::TestAddedMass2D::test_AddedMass_2D 
[gw0] [ 37%] FAILED proteus/tests/AddedMass/test_addedmass3D.py::TestAddedMass3D::test_AddedMass_3D 
[gw0] [ 49%] FAILED proteus/tests/amg_tests/test_amg_methods.py::test_amg_iteration_matrix_1 
[gw0] [ 50%] FAILED proteus/tests/amg_tests/test_amg_methods.py::test_amg_iteration_matrix_2 
\cc @alistairbntl @tridelat

**Comment by tridelat** [comment]
@cekees I fixed the added mass and gmsh tests. For gmsh, the 2D test had to have its number of nodes/edges/elements changed slightly, not sure why but it could be that gmsh 4 leads to a slightly different mesh in 2D (it did not seem to be a problem in 3D)

**Comment by cekees** [comment]
Thanks @tridelat . @alistairbntl I updated the getSubMatrix -> createSubmatrix on this branch. I'm guessing you have have that change in one of your working branches. @manuel-quezada there are problems with the rdls tests because the solvers were set to parallel but not petsc options were provided, so the solvers behavior has changed enough in petsc 3.10 that the comparisons fail. It looks to me like you just pasted in the max sdf value from the computed version that you trusted it. I have updated the tests to use petsc but explicitly specify superlu. Could also just set parallel=False. Can you verify that the tests are actually working? These are the last test fixes needed.

**Comment by alistairbntl** [comment]
@cekees That is correct, I had been working on the branch https://github.com/erdc/proteus/tree/alistairbntl/update_to_petsc_3.10.2 .  I don't think there is much else that is different between the two now, but I just pushed up my latest changes.

**Pull request merged**
