### PR TITLE
Docker no opt

### PR DESCRIPTION
**Pull request by cekees**
# Mandatory Checklist

Please ensure that the following criteria are met:

- [ ] Title of pull request describes the changes/features
- [ ] Request at least 2 reviewers
- [ ] If new files are being added, the files are no larger than 100kB. Post the file sizes.
- [ ] Code coverage did not decrease. If this is a bug fix, a test should cover that bug fix. If a new feature is added, a test should be made to cover that feature.
- [ ] New features have appropriate documentation strings (readable by sphinx)
- [ ] Contributor has read and agreed with CONTRIBUTING.md and has added themselves to CONTRIBUTORS.md 

As a general rule of thumb, try to follow [PEP8](https://www.python.org/dev/peps/pep-0008/) guidelines.

# Description

### CODE REVIEW

**Comment by cekees** [comment]
@zhang-alvin and @JohanMabille I think I'm just going to close this because I've not been able to find any tricks to reduce the gcc memory usage enough to re-enable auto builds on docker hub, which has a 2GM limit on RAM.  It does show 1) an approach to splitting up the RANS* classes, in a way that I think is reasonable and does reduce the memory usage enough to allow some parallel builds--just still not enough reduction, and 2) a small change to the way parallel builds are done, which is to force the python parallel builds to use only N processes instead of grabbing all the cores. For now, using all the cores on my laptop still uses too much memory to complete the proteus build.

**Comment by zhang-alvin** [comment]
@cekees I'm fine with that. I'll go ahead and try spinning up a buildbot to take care of the Docker container builds to autopush to docker hub.

**Comment by JohanMabille** [comment]
@cekees I am working on splitting the RANS module.

**Comment by JohanMabille** [comment]
@cekees I am working on the split of the RANS module so we can try to  switch back to -O2 or -O3 flags in travis-ci.

**Comment by cekees** [comment]
Thanks @JohanMabille. On the last commit I still got the out of memory error for RANS3PSed (already split, so just the 3D class):

```bash
mpicc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -w -fPIC -I/home/jovyan/proteus/linux/include/python3.7 -I/home/jovyan/.local/include/python3.7 -I/home/jovyan/proteus/linux/lib/python3.7/site-packages/numpy/core/include -I/home/jovyan/proteus/linux/include -I/home/jovyan/proteus/linux/Library/include -Iproteus -Iproteus/xtensor/pybind11/include -Iproteus/xtensor/xtensor-python/include -Iproteus/xtensor/xtensor/include -Iproteus/xtensor/xtl/include -I/home/jovyan/proteus/linux/include/python3.7 -c proteus/mprans/cRANS3PSed.cpp -o build/temp.linux-x86_64-3.7/proteus/mprans/cRANS3PSed.o -DNDEBUG -g0 -O0 -std=c++14
virtual memory exhausted: Cannot allocate memory
```
At various points I also tried some gcc options that affect the compiler garbage collection, to no avail. I think the current design simply requires that much memory, so hope hopefully your changes to the design will fix this in the next iteration..

**Comment by cekees** [comment]
@zhang-alvin and @tridelat the path of least resistance for automated builds may be to just add another travis build stage to build and push the docker image: https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry. Testing out an alternative service like CircleCI or Shippable, which allow use of custom docker images for builds as well, might also be worth the time.

**Comment by JohanMabille** [comment]
> On the last commit I still got the out of memory error for RANS3PSed (already split, so just the 3D class):

I think this is why we switched from -O3 to -O2. I have split RANS3PF (the one that was not building, even with -O2), let's see what the CI say (PR incoming).

**Pull request closed without merging**
