### PR TITLE
Mquezada/SWFlows

### PR DESCRIPTION
**Pull request by manuel-quezada**
Non intrusive PR for running Shallow Water problems easily. The idea is to share the _so, _p and _n files for all the problems.

### CODE REVIEW

**Comment by cekees** [comment]
@ejtovar I've updated the branch to get this ready to  review/refactor but there are a few tests failing now for SWE, for  simple reasons, I think. Could you take look?
[gw0] [ 47%] FAILED proteus/tests/SWFlows/test_SWFlows.py::TestSWFlows::test_solitary 
[gw0] [ 48%] FAILED proteus/tests/SWFlows/test_SWFlows.py::TestSWFlows::test_parab1D 
[gw0] [ 48%] FAILED proteus/tests/SWFlows/test_SWFlows.py::TestSWFlows::test_dam3Bumps

**Comment by cekees** [comment]
@ejtovar and @manuel-quezada the SWCV.h implementations have the same issues as the TwoPhaseFlow PR in terms of allocation of large arrays on the stack (e.g. register double[numDOFs]).

**Comment by cekees** [comment]
The tests are initially failing in travis because the SWE app tests are written in such a way that they can only be called from inside that specific directory.The tests need to be written so they can be called from anywhere (e.g. py.test FULL_PATH_TO_TEST.py).  I put in a fix for that, but the tests are still failing for the app. @manuel-quezada and @ejtovar can you take a look at `tests/SWFlows` and see why just those three tests fail to match the reference data?

**Comment by manuel-quezada** [comment]
I figured the problem about the location of the tests in the `TwoPhaseFlow` PR and fixed it there but not here. About the tests, they might be failing just because of known changes on the code. I think this PR was open since before I went the last time to TAMU to incorporate convex limiting so I would not worry much about it. But maybe it is safe to run all tests for longer times and make sure that the solutions look fine. @ejtovar can you take care of that?

**Comment by ejtovar** [comment]
Yes, I can look into it @manuel-quezada and @cekees.

**Pull request merged**
