### PR TITLE
initial issues with python3

### PR DESCRIPTION
**Pull request by cekees**
This branch is ready for testing by others. There are some tests failing, which I'll list below, but travis is also working now, so you can look at the travis output.  @burgreen  you can start using this for your HPC work.

Notes:
- You need a python3 stack, which you can get by ensuring the `./stack` submodule is on the python3 branch (e.g. `cd stack; git checkout master; rm default.yaml` ) 
- You need a system python3 interpreter in order for the Makefile to work properly
-  Python3 indentifies linux systems as linux unlike linux2, so the stack gets put in `./linux` now.
-  The `reload` command used often in tests needs to come from importlib in python

Remaining tests failures:

Chrono issues (@tridelat ). These are due to string handling in the Cython extension.
proteus/tests/test_mbd_chrono.py::TestCable::testHangingCableANCF 
proteus/tests/AddedMass/test_addedmass2D.py::TestAddedMass2D::test_AddedMass_2D 
proteus/tests/AddedMass/test_addedmass3D.py::TestAddedMass3D::test_AddedMass_3D 

Sed testing issues (@adimako ). 
proteus/tests/test_sedclosure.py::TestHsu::testMintFluid 
proteus/tests/test_sedclosure.py::TestHsu::testMintSolid 
proteus/tests/test_sedclosure.py::TestHsu::testMintgradC 

EV issues (@ejtovar and @manuel-quezada ).
proteus/tests/CLSVOF/with_RANS2P/test_clsvof_with_rans2p.py::TestCLSVOFWithRans2p::test_2D_multiphase 
proteus/tests/ProjScheme_with_EV/test_ns_convergence.py::TestProjScheme::test_edge_based_visc_1 
proteus/tests/ProjScheme_with_EV/test_ns_convergence.py::TestProjScheme::test_edge_based_visc_2
proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_dam_over_bumps 
proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_oneD_dambreak_flat_bottom 
proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_oneD_paraboloid_with_friction 
proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_twoD_paraboloid_with_friction 
proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_gauges 
proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_reflecting_BCs 

MeshAdapt (@zhang-alvin ). Needs to be renabled in build and checked.

proteus/tests/MeshAdaptPUMI/test_gmshCheck.py::test_gmshLoadAndAdapt 
proteus/tests/MeshAdaptPUMI/test_gmshCheck.py::test_2DgmshLoadAndAdapt 
proteus/tests/MeshAdaptPUMI/test_gmshCheck.py::test_2DmultiRegion 
proteus/tests/MeshAdaptPUMI/test_meshLoad.py::test_meshLoadPUMI 
proteus/tests/MeshAdaptPUMI/test_poiseuilleError.py::test_poiseuilleError 
proteus/tests/MeshAdaptPUMI/gauge_compare/dambreak_Colagrossi_2D/test_MeshAdaptRestart.py::test_MeshAdaptRestart 

 
proteus/tests/cylinder2D/conforming_rans2p/test_cylinder2D_conforming_rans2p.py::Test_rans2p::test_ex2 

BDM and quad support (@alistairbntl ). Could have uncovered a subtle indexing error or and issue with the python2-3 change in / operator:
proteus/tests/post_processing/test_bdm2_3d_mesh.py::TestBDM2Mesh3D::test_BDM2_reference_triangle_full_in_space 
proteus/tests/post_processing/test_bdm2_mesh8.py::TestBDM2Mesh8::test_BDM2_reference_triangle_full_in_space 
proteus/tests/post_processing/test_bdm_projection.py::TestBDM2Reference1::test_BDM2_reference_triangle_full_in_space 
proteus/tests/post_processing/test_bdm_projection.py::TestBDM2Reference1::test_BDM2_reference_triangle_full_not_in_space 
proteus/tests/post_processing/test_elementwise_flux.py::TestElementwiseFlux2D::test_BDM2_reference_triangle_full_in_space 
proteus/tests/mesh_tests/test_quads.py::test_mesh_build 
proteus/tests/mesh_tests/test_quads.py::test_calc_hmax 
proteus/tests/mesh_tests/test_quads.py::test_buildNodeDiameterArray_1 

Others:
proteus/tests/griffiths_lane_6/test_griffiths_lane6.py::TestRichards::test_richards 
proteus/tests/HotStart_3P/test_HotStart_rans3p.py::Test_HotStart_rans3p::test_hotstart_p1 
proteus/tests/HotStart_3P/test_HotStart_rans3p.py::Test_HotStart_rans3p::test_hotstart_p2

### CODE REVIEW

**Comment by cekees** [comment]
Chrono issues (@tridelat ). These are due to string handling in the Cython extension. I added a bunch of fixes for the string handling, which is a bit tricky. There might be a more elegant way to handle it. The added mass tests are failing because of the numerical error relative to the comparison, so it may be related to older/deeper issues with the added mass. We can work on it next week.

- [x] proteus/tests/test_mbd_chrono.py::TestCable::testHangingCableANCF 
- [ ] proteus/tests/AddedMass/test_addedmass2D.py::TestAddedMass2D::test_AddedMass_2D
- [ ] proteus/tests/AddedMass/test_addedmass3D.py::TestAddedMass3D::test_AddedMass_3D

**Comment by cekees** [comment]
Sed testing issues (@adimako ). I changed the tests to use the numpy's array testing syntax. I don't think the tests using all() and round were actually testing anything, since v.all() just checks that all elements are positive.

- [x] proteus/tests/test_sedclosure.py::TestHsu::testMintFluid
- [x] proteus/tests/test_sedclosure.py::TestHsu::testMintSolid
- [x] proteus/tests/test_sedclosure.py::TestHsu::testMintgradC

**Comment by cekees** [comment]
EV issues (@ejtovar and @manuel-quezada ). I fixed the SWE errors but am still not sure why the EV and CLSVOF is failing. I suspect with @tridelat that there may be some subtle issue with the clsvof and/or rans3p recently added to master. Moses also seems to fail sometimes.

- [ ] proteus/tests/CLSVOF/with_RANS2P/test_clsvof_with_rans2p.py::TestCLSVOFWithRans2p::test_2D_multiphase
- [ ] proteus/tests/ProjScheme_with_EV/test_ns_convergence.py::TestProjScheme::test_edge_based_visc_1
- [ ] proteus/tests/ProjScheme_with_EV/test_ns_convergence.py::TestProjScheme::test_edge_based_visc_2
- [x] proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_dam_over_bumps
- [x] proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_oneD_dambreak_flat_bottom
- [x] proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_oneD_paraboloid_with_friction
- [x] proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_twoD_paraboloid_with_friction
- [x] proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_gauges
- [x] proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_reflecting_BCs

**Comment by cekees** [comment]
MeshAdapt (@zhang-alvin ). I re-enabled and fixed the string handling in the .pyx.

- [x] proteus/tests/MeshAdaptPUMI/test_gmshCheck.py::test_gmshLoadAndAdapt
- [x] proteus/tests/MeshAdaptPUMI/test_gmshCheck.py::test_2DgmshLoadAndAdapt
- [x] proteus/tests/MeshAdaptPUMI/test_gmshCheck.py::test_2DmultiRegion
- [x] proteus/tests/MeshAdaptPUMI/test_meshLoad.py::test_meshLoadPUMI
- [x] proteus/tests/MeshAdaptPUMI/test_poiseuilleError.py::test_poiseuilleError
- [x] proteus/tests/MeshAdaptPUMI/gauge_compare/dambreak_Colagrossi_2D/test_MeshAdaptRestart.py::test_MeshAdaptRestart

**Comment by cekees** [comment]
Others:
- [x] proteus/tests/griffiths_lane_6/test_griffiths_lane6.py::TestRichards::test_richards
- [x] proteus/tests/HotStart_3P/test_HotStart_rans3p.py::Test_HotStart_rans3p::test_hotstart_p1
- [x] proteus/tests/HotStart_3P/test_HotStart_rans3p.py::Test_HotStart_rans3p::test_hotstart_p2

**Comment by cekees** [comment]
BDM and quad support (@alistairbntl ). I fixed one actual bug in the quad mesh generation in Python. Thee test_quads now pass locally, but fail when I run the whole test set. Not sure what is going on with the BDM2 support.

- [ ] proteus/tests/post_processing/test_bdm2_3d_mesh.py::TestBDM2Mesh3D::test_BDM2_reference_triangle_full_in_space
- [ ] proteus/tests/post_processing/test_bdm2_mesh8.py::TestBDM2Mesh8::test_BDM2_reference_triangle_full_in_space
- [ ] proteus/tests/post_processing/test_bdm_projection.py::TestBDM2Reference1::test_BDM2_reference_triangle_full_in_space
- [ ] proteus/tests/post_processing/test_bdm_projection.py::TestBDM2Reference1::test_BDM2_reference_triangle_full_not_in_space
- [ ] proteus/tests/post_processing/test_elementwise_flux.py::TestElementwiseFlux2D::test_BDM2_reference_triangle_full_in_space
- [ ]  proteus/tests/mesh_tests/test_quads.py::test_mesh_build
- [ ] proteus/tests/mesh_tests/test_quads.py::test_calc_hmax
- [ ] proteus/tests/mesh_tests/test_quads.py::test_buildNodeDiameterArray_1

**Comment by cekees** [comment]
Thanks @alistairbntl. I think I can fix the rest.

**Comment by alistairbntl** [comment]
@cekees - It looked to me that the PETSc options for the twophase flow were still failing.  I was going to take that on on Sunday.  Of the remaining tests that were failing, I didn't notice anything directly related to the solver stuff.  If something comes up let me know, my schedule has opened up a great deal after today.

**Comment by alistairbntl** [comment]
@cekees @tridelat - 
It seems that the .h5 output changed somewhat between python 2 and 3 for the `damBreak_solver_options` test in the TwoPhaseFlow module.  Specifically, the error tolerance using the `python2` solution was only accurate to 1e-4.  Have you experienced this type of behavior in the migration from 2 to 3.
For the time being, I updated the .h5 file so that the test passes (commit - b2f78f3).  If the change is in fact a concern, let me know so that I can investigate the change more carefully.

**Comment by cekees** [comment]
@manuel-quezada there's one test failing on clsvof here that seems to be a non-trivial difference in the comparison files: proteus/tests/CLSVOF/with_RANS2P/test_clsvof_with_rans2p.py

Here's the difference in phi between the computed solution and the comparison data
error_clsvof

**Comment by cekees** [comment]
@alistairbntl This looks like an issue with the pcd solver options, since the rest of the two-phase tests are passing: proteus/tests/TwoPhaseFlow/test_TwoPhaseFlow.py::TestTwoPhaseFlow::test_damBreak_solver_options
They may just need to be tighter for the np.allclose tolerances.
/cc @manuel-quezada  @tridelat

**Pull request merged**
