### PR TITLE
Add Bernstein FE spaces

### PR DESCRIPTION
**Pull request by manuel-quezada**
PR to incorporate and test Bernstein FE spaces

### CODE REVIEW

**Comment by manuel-quezada** [comment]
Hi @cekees, can you take a look at this PR? I hope it is not a big one. Basically I duplicate some structure from FemTools to include Bernstein polynomials on quads and simplices. The definition of the polynomials is arbitrary wrt the order but the spaces are constructed for quadratic polynomials. I think this is true also for Lagrange polynomials.

**Comment by manuel-quezada** [comment]
@cekees I wonder if this travis errors are related to the same problem in the other PR. It seems the compilation also failed due to being too long.

**Comment by manuel-quezada** [comment]
@cekees I added the __init__.py file that we discussed but the tests are still not being run. Do you  have any ideas on what might be happening?

**Comment by manuel-quezada** [comment]
@alistairbntl I did the changes you suggested. Let's see if this works out. Thanks for your help.

**Comment by manuel-quezada** [comment]
@cekees , finally all checks passed. Do I have green light to merge it or do you want me to wait until you merge the 2nd clean up?

**Comment by cekees** [comment]
Go ahead and merge

**Pull request merged**
