### PR TITLE
Release candidate 1.7.5

### PR DESCRIPTION
**Pull request by cekees**
# Mandatory Checklist

Please ensure that the following criteria are met:

- [x] Title of pull request describes the changes/features
- [x] Request at least 2 reviewers
- [x] If new files are being added, the files are no larger than 100kB. Post the file sizes.
- [x] Code coverage did not decrease. If this is a bug fix, a test should cover that bug fix. If a new feature is added, a test should be made to cover that feature.
- [x] New features have appropriate documentation strings (readable by sphinx)
- [x] Contributor has read and agreed with CONTRIBUTING.md and has added themselves to CONTRIBUTORS.md 

As a general rule of thumb, try to follow [PEP8](https://www.python.org/dev/peps/pep-0008/) guidelines.

# Description

### CODE REVIEW

**Comment by cekees** [comment]
@zhang-alvin the name change of MeshAdapt.pyx to Adapter.pyx was breaking the documentation generation because the extension module was still named MeshAdapt.pyx. Maybe when wrapping up one of the other PR's you can make the change to Adapter just making sure you change the setup.py file and whatever python modules depend on MeshAdapt/Adapter. Unless I misunderstood what is going on here.

**Comment by cekees** [comment]
@ejtovar in reviewing the docs I found an extra "SWFlows" file, which I removed because it wasn't being used. The current docs use the "Green-Naghdi" naming scheme so I guess if we want to be consistent width the papers we should do some editing so  the paper and a future release are using the same terminology.

**Comment by cekees** [comment]
> Didn't know that there'd be an issue with documentation. I'll redo the name change at a later PR.

Thanks, I should have been more specific: it just shows up as a warning when generating the webpage page but then also creates a broken link. I believe sphinx load all the modules for the package with python bug then actually parses the pyx files for the docstrings or something along those lines. With the proteus module named MeshAdapt but the pyx file for named Adapter, it seems to get confused.

**Comment by ejtovar** [comment]
> @ejtovar in reviewing the docs I found an extra "SWFlows" file, which I removed because it wasn't being used. The current docs use the "Green-Naghdi" naming scheme so I guess if we want to be consistent width the papers we should do some editing so the paper and a future release are using the same terminology.

Do you want me to make the changes for this release or a different one?

**Review by ejtovar — APPROVED** [review]
Looks good to me!

**Pull request merged**
