### PR TITLE
mquezada/Change macros to inline functions 

### PR DESCRIPTION
**Pull request by manuel-quezada**
In this PR I will handle issue #819.

### CODE REVIEW

**Comment by cekees** [comment]
I don't think you need (or generally would want) the "using" statements exposing the new function definitions in the header file. Since you're using the functions within the proteus namespace anyway they should already be available where they are needed.  This is my bad, since I pointed you to an example where I put  "using proteus::f"  in the header, but that was only because there were other macros that depended on the definition of "f".  Now that you've got them all defined as inline functions, I believe you can get rid of those "using" statements, which will make the code safer, as intended. Basically, "using proteus::func" in the header file is going to expose func to other things that include the header, which defeats the purpose of enclosing in a namespace.

**Comment by manuel-quezada** [comment]
I see. So the whole idea is to make those functions not visible outside of their respective .h file, right? by doing `using proteus` I was making them visible again.

**Comment by manuel-quezada** [comment]
I included tests for the SWEs before changing from the macros to the inline functions. Once they pass I will change SW2DCV.h as well. This implementation of SW2DCV is the most recent I have (i.e., with convex limiting). I am off course not including anything about sharing _p and _n files.

**Comment by manuel-quezada** [comment]
@cekees I added the SWEs tests and changed most of the macros to inline functions within SW2DCV.h. However, there are two more I need to change but for some reason when I change those the tests don't pass. It seems the macro and the inline functions are not giving the same thing. Can you take a look to see if you spot something? I will keep investigating as well.

**Pull request merged**
