### PR TITLE
Yy/sbm/asserterr

### PR DESCRIPTION
**Pull request by wacyyang**
In this PR, the following changes are made:

- simplify the computation of `middle_point_coord `
- `dist` may be negative
- replace `assert(ebN>=nElementBoundaries_owned)`
- update `.h5` files

### CODE REVIEW

**Comment by cekees** [comment]
the tests are failing because the hdf5 file comparison files don't have the same number of quadrature points as what is being run. Run git diff ane make sure you have no changes locally.

**Comment by wacyyang** [comment]
@cekees It looks weird. I am not sure what is wrong here. This is what I get on my laptop. 
screenshot 2018-08-22 21 07 07

**Comment by cekees** [comment]
what changes did you make to the Makefile?

**Comment by wacyyang** [comment]
It is the definition of `FC` 
screenshot 2018-08-22 21 44 31

**Comment by cekees** [comment]
It appears that the mesh generated on your machine and the testing image are different.

**Pull request merged**
