### PR TITLE
Python 2 to 3 fixes

### PR DESCRIPTION
**Pull request by davidbrochart**
- `str` has no attribute `decode` in Python 3.
- `createArray` becomes `create_array` in Python 3.

### CODE REVIEW

**Comment by davidbrochart** [comment]
I wanted to have the notebooks working on Binder from my fork, and I don't have forked the submodules, so it cannot build. Let me see if that works if I fork them.

**Comment by cekees** [comment]
I see, that sounds like a good plan. There are other ways for us to handle the sub modules and Dockerfile using the hashdist stack, if needed. I think it’s good for you to run with your approach until you’re happy with it.

**Comment by davidbrochart** [comment]
@cekees I have a binder working: https://mybinder.org/v2/gh/davidbrochart/proteus/fix?filepath=notebooks%2FTutorials%2FTutorial_1%2FIntroduction.ipynb
It's using my branch on my fork of proteus, and the packages installed through conda-forge.

**Comment by davidbrochart** [comment]
@cekees What prevents this PR to be merged at the moment is the handling of the sub modules and Dockerfile. You mentioned using the hashdist stack, what do you have in mind?
Once this is merged, we would need to make a Proteus release to be able to install through conda-forge.

**Comment by davidbrochart** [comment]
@cekees I reverted the deletion of the submodules and the Dockerfile, so it cannot work in Binder anymore. But once this is merged and released you should be able to run the tutorial notebooks locally through conda-forge installation.

**Comment by cekees** [comment]
Thanks. We can reconfigure this binder repo to use the conda package: https://github.com/erdc/proteus_tutorial

I'd be interested in the different in the startup time relative to the current docker container.

**Comment by davidbrochart** [comment]
Thanks for merging @cekees. Could you please also make a release? This is required if we want to have the changes in conda-forge.

**Comment by davidbrochart** [comment]
Ping @cekees

**Comment by cekees** [comment]
Done, thanks to @tridelat  !

**Comment by davidbrochart** [comment]
Thanks @cekees and @tridelat !

**Comment by tridelat** [comment]
Actually would need to re-release this one. It is only for "cosmetic" changes referring to version `1.7.1` instead of `1.7.0.dev0`. I can release with the same tag, as long as it does not create problems with conda-forge @davidbrochart

**Comment by davidbrochart** [comment]
@tridelat Proteus 1.7.1 is now available through conda-forge: https://anaconda.org/conda-forge/proteus
@cekees You can try the following binder that uses it: https://mybinder.org/v2/gh/davidbrochart/proteus_tutorial/master?filepath=index.ipynb

**Comment by davidbrochart** [comment]
@cekees Sorry, I meant this binder: https://mybinder.org/v2/gh/davidbrochart/proteus_tutorial/conda_forge?filepath=index.ipynb

**Pull request merged**
