### PR TITLE
eric/Dispersive_SWEs

### PR DESCRIPTION
**Pull request by ejtovar**
First pull request for the work on the dispersive Shallow Water Equations (or modified Green-Naghdi equations). This PR includes:

- the ability to use the DSWEs in the SWFlows app
- new tests found in SWFlows/test
- a README file for the SWFlows app with instructions on how to run the test

Note that the DSWEs additions are not release ready.

### CODE REVIEW

**Comment by cekees** [comment]
```
[gw0] [ 46%] FAILED proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_dam_over_bumps 
[gw0] [ 46%] FAILED proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_oneD_dambreak_flat_bottom 
[gw0] [ 46%] FAILED proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_oneD_paraboloid_with_friction 
[gw0] [ 46%] PASSED proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_twoD_paraboloid_with_friction 
[gw0] [ 47%] FAILED proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_gauges 
[gw0] [ 47%] FAILED proteus/tests/SWEs/test_SWEs.py::TestSWEs::test_reflecting_BCs 
[gw0] [ 47%] FAILED proteus/tests/SWFlows/test_SWFlows.py::TestSWFlows::test_solitary 
[gw0] [ 47%] FAILED proteus/tests/SWFlows/test_SWFlows.py::TestSWFlows::test_parab1D 
[gw0] [ 48%] FAILED proteus/tests/SWFlows/test_SWFlows.py::TestSWFlows::test_dam3Bumps 
```

**Comment by ejtovar** [comment]
I didn't change anything in the regular Shallow Water files (besides just clang formatting), so I'm not sure why the tests are failing. Let me look into this issue. 

Also, @manuel-quezada, in lines 2079 and 2103 of the SW2DCV.h file, should those terms be the source terms for **hv** and not **hu**?

**Comment by manuel-quezada** [comment]
@ejtovar you might be right. However, I wonder if we should not consider these terms at all since they are added explicitly during the convex limiting step. But, as they are now, that seems inconsistent. I agree with you on that. So we should either fix them as you proposed or delete them completely. Have you implemented either FCT or convex limiting with your model? Maybe once you do that it will be clear what the fix should be.

**Comment by ejtovar** [comment]
@manuel-quezada I was having some issues with the FCT/CL and I think maybe the extended source terms might have been the culprit. I will continue investigating and hopefully find the best approach.

**Comment by cekees** [comment]
Just  checking in on what's going on here.  Did you just need to git  add the "good" comparison files? Can you get that done in the next  few days?

**Comment by ejtovar** [comment]
Hey Chris, I'm actually working on this right now. There were typos in some other parts of the Shallow Water files that I'm working on correcting.

**Comment by tridelat** [comment]
@cekees I agree for the issue raising alternative, @ejtovar could you raise it and list what was missing for this PR?
I will merge this one and update the 1.6.1 PR

**Pull request merged**
