### PR TITLE
adding numdiff lines to RANS2P.h and RANS2P2D.h, reverting rdls toler…

### PR DESCRIPTION
**Pull request by jhcollins**
…ance back to 0.1*he in TwoPhaseFlow.py

# Mandatory Checklist

Please ensure that the following criteria are met:

- [ ] Title of pull request describes the changes/features
- [ x] Request at least 2 reviewers
- [ ] If new files are being added, the files are no larger than 100kB. Post the file sizes.
- [ ] Code coverage did not decrease. If this is a bug fix, a test should cover that bug fix. If a new feature is added, a test should be made to cover that feature.
- [ ] New features have appropriate documentation strings (readable by sphinx)
- [x ] Contributor has read and agreed with CONTRIBUTING.md and has added themselves to CONTRIBUTORS.md 

As a general rule of thumb, try to follow [PEP8](https://www.python.org/dev/peps/pep-0008/) guidelines.

# Description

### CODE REVIEW

**Comment by zhang-alvin** [comment]
Let me try duplicating the result on a docker container.

**Comment by zhang-alvin** [comment]
Just kidding, I don't think it's  [possible](https://stackoverflow.com/questions/40824547/docker-image-running-a-mac-os-x-installation#:~:text=If%20you%20are%20trying%20to,Mac%20OS%20in%20Docker%20container)

**Comment by zhang-alvin** [comment]
@cekees It looks like restarting the build is insufficient. Considering the small number of changes, I'm quite alright with simply skipping that test and having someone with osx actually take a closer look to understand the effects of the diff.

**Comment by cekees** [comment]
OK with me. @jhcollins do you want to just put in a line in .travis.yaml to exclude that test on osx? @ejtovar whenever you get a chance, could you please run that test and see if it fails on your machine?

**Comment by zhang-alvin** [comment]
Going to go ahead and merge this. @ejtovar feel free to add your observations in this chain even if the PR is closed.

**Comment by jhcollins** [comment]
Thanks alvin. I was holding off until eric could check it out, but im fine with merging 👍

**Pull request merged**
