### PR TITLE
Adding proteus_tutorial repo as a submodule in proteus/tests/

### PR DESCRIPTION
**Pull request by jhcollins**
# Mandatory Checklist

Please ensure that the following criteria are met:

- [x] Title of pull request describes the changes/features
- [x] Request at least 2 reviewers
- [x] If new files are being added, the files are no larger than 100kB. Post the file sizes.
- [x] Code coverage did not decrease. If this is a bug fix, a test should cover that bug fix. If a new feature is added, a test should be made to cover that feature.
- [x] New features have appropriate documentation strings (readable by sphinx)
- [x] Contributor has read and agreed with CONTRIBUTING.md and has added themselves to CONTRIBUTORS.md 

As a general rule of thumb, try to follow [PEP8](https://www.python.org/dev/peps/pep-0008/) guidelines.

# Description
As part of the addition of the proteus_tutorial simulations to the tests, I am including the repo as a submodule in proteus/tests. Happy to move it wherever you see fit.

No new files
Code coverage does not decrease
No new feature

### CODE REVIEW

**Comment by jhcollins** [comment]
The tests I wrote are failing on travis but working locally so I'm in the middle of debugging that

**Comment by jhcollins** [comment]
okay, the proteus_tutorials tests are now resulting in the expected behavior (i.e. pass for non moving mesh, fail for moving mesh)

**Comment by zhang-alvin** [comment]
@jhcollins, great. Thanks for this. 

On my end, there's still a bit of a hiccup with the parallel run on the fix.

**Comment by jhcollins** [comment]
@zhang-alvin is the change you requested correct? if so, would you mind approving it?

**Comment by zhang-alvin** [comment]
> @zhang-alvin is the change you requested correct? if so, would you mind approving it?

It looks right.

**Comment by jhcollins** [comment]
Thanks. The parallel floating body test just passed btw

**Pull request closed without merging**
