### PR TITLE
Changes to SWFlow solvers

### PR DESCRIPTION
**Pull request by ejtovar**
This PR includes changes to the SWFlow solvers. More specifically, it updates the numerical solver for the hyperbolic Serre--Green-Naghdi solver to be more robust and effecient.

# Mandatory Checklist

Please ensure that the following criteria are met:

- [x ] Title of pull request describes the changes/features
- [ ] Request at least 2 reviewers
- [ ] If new files are being added, the files are no larger than 100kB. Post the file sizes.
- [ ] Code coverage did not decrease. If this is a bug fix, a test should cover that bug fix. If a new feature is added, a test should be made to cover that feature.
- [ ] New features have appropriate documentation strings (readable by sphinx)
- [ ] Contributor has read and agreed with CONTRIBUTING.md and has added themselves to CONTRIBUTORS.md 

As a general rule of thumb, try to follow [PEP8](https://www.python.org/dev/peps/pep-0008/) guidelines.

# Description

### CODE REVIEW

**Review by cekees — APPROVED** [review]

**Comment by cekees** [comment]
If proteus/tests/single_phase_gw/test_single_phase_gw.py::TestSinglePhaseGW::test_ncp1 fails again on os x, you can just add a skip statement for osx, @ejtovar . Thanks for all your work on this PR!

**Comment by cekees** [comment]
> If proteus/tests/single_phase_gw/test_single_phase_gw.py::TestSinglePhaseGW::test_ncp1 fails again on os x, you can just add a skip statement for osx, @ejtovar . Thanks for all your work on this PR!

Any luck with this @ejtovar ? Looks like it is not passing upon rerunning. I'd just disable that test...

**Comment by ejtovar** [comment]
> > If proteus/tests/single_phase_gw/test_single_phase_gw.py::TestSinglePhaseGW::test_ncp1 fails again on os x, you can just add a skip statement for osx, @ejtovar . Thanks for all your work on this PR!
> 
> Any luck with this @ejtovar ? Looks like it is not passing upon rerunning. I'd just disable that test...

This test isn't using `pytest`. Any recommendations on how to skip it?

**Comment by cekees** [comment]
> > > If proteus/tests/single_phase_gw/test_single_phase_gw.py::TestSinglePhaseGW::test_ncp1 fails again on os x, you can just add a skip statement for osx, @ejtovar . Thanks for all your work on this PR!
> > 
> > 
> > Any luck with this @ejtovar ? Looks like it is not passing upon rerunning. I'd just disable that test...
> 
> This test isn't using `pytest`. Any recommendations on how to skip it?

I think you just need to import pytest. All the tests are using pytest whether they were originally designed for pytest or not. I see:

____ ERROR collecting proteus/tests/single_phase_gw/test_single_phase_gw.py ____

proteus/tests/single_phase_gw/test_single_phase_gw.py:26: in <module>

    class TestSinglePhaseGW(object):

proteus/tests/single_phase_gw/test_single_phase_gw.py:75: in TestSinglePhaseGW

    @pytest.mark.skipif(os.getenv('TEST_PROFILE')=="proteus-conda-osx", reason="need to fix locally on osx")

E   NameError: name 'pytest' is not defined

**Pull request merged**
