### PR TITLE
Enable OSX tests

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by cekees** [comment]
@ejtovar and I looked at this a little bit at one point.  I believe the build actually seems to be fine, by pytest crashes for some reason.

**Comment by davidbrochart** [comment]
@cekees I will have a look at it on the Mac machine we have at the office.
@ejtovar do you use the conda proteus environment (dev or not) on your Mac? How is it working?

**Comment by ejtovar** [comment]
@davidbrochart Yes, I am using the conda dev environment, but I disabled the pychrono dependencies. Everything seems to be working fine.

**Comment by davidbrochart** [comment]
You know the OSX build works with pychrono now?

**Comment by ejtovar** [comment]
Yes I did see that, but I have not tried it yet.

**Comment by cekees** [comment]
@ejtovar could you help @davidbrochart wrap this up? I think we're nearly have some of the refactoring and testing behind us so we can get back to development. Would be nice to have the osx build tracking with full testing support.

**Comment by ejtovar** [comment]
Yes no problem, I will look into it this afternoon. @davidbrochart what is the current status? Maybe we can discuss on Slack and try to wrap this up.

**Comment by davidbrochart** [comment]
I opened a new PR in #1147 (I still have issues with files that should be pointers in my reop).
pytest just exits with (https://travis-ci.com/github/erdc/proteus/jobs/323706514):
```
collecting 272 items
The command "py.test --forked -v proteus/tests --ignore proteus/tests/POD" exited with 59.
```

**Comment by cekees** [comment]
addressed by #1178

**Pull request closed without merging**
