### PR TITLE
Pllugged ArgumentsDict into SW2DCV

### PR DESCRIPTION
**Pull request by JohanMabille**
# Mandatory Checklist

Please ensure that the following criteria are met:

- [ ] Title of pull request describes the changes/features
- [ ] Request at least 2 reviewers
- [ ] If new files are being added, the files are no larger than 100kB. Post the file sizes.
- [ ] Code coverage did not decrease. If this is a bug fix, a test should cover that bug fix. If a new feature is added, a test should be made to cover that feature.
- [ ] New features have appropriate documentation strings (readable by sphinx)
- [ ] Contributor has read and agreed with CONTRIBUTING.md and has added themselves to CONTRIBUTORS.md 

As a general rule of thumb, try to follow [PEP8](https://www.python.org/dev/peps/pep-0008/) guidelines.

# Description

### CODE REVIEW

**Comment by ejtovar** [comment]
I think we can merge this once the SWEs tests pass. It looks like they're still failing.

**Comment by JohanMabille** [comment]
The failure is due to arguments type mismatch: a double is expected on the C++ side while an int is passed from the Python. Before using the dictionaries, the conversion was automatic and everything worked fine. Now the parameter ends up in the wrong scalar dictionary. When asking for this scalar in C++, since it is not found in the map, a default value is returned.

We need to catch these bugs quickly, I will improve the dictionaries for scalar in a dedicated PR and rebase all the failing PRs on it once it is merged (the other failures are probably due to the same issue).

**Comment by JohanMabille** [comment]
See #1157

**Comment by JohanMabille** [comment]
@ejtovar I think this one is ready for a merge.

**Comment by ejtovar** [comment]
Thanks @JohanMabille!

**Pull request merged**
