### PR TITLE
[WIP] TPF: sketch of initial conditions refactoring

### PR DESCRIPTION
**Pull request by zhang-alvin**
This PR is a draft of how the initial condition refactoring might be done in TPF as per issue #1069.

The idea is to force the user to supply initial conditions for each model based on hard-coded keywords. 

This deviates from the previous approach in that user now cannot use integers to associate an initial condition with a model variable, e.g. `{0: foo()}` would now be `{'p': foo()}` to denote the pressure initial condition.

I've only done the modifications necessary to get the `RANS2P` model compliant to solicit some feedback as it would take some time to implement this across the board.

### CODE REVIEW

**Comment by zhang-alvin** [comment]
@cekees and @tridelat would be good to have a brief look before the developer call.

**Comment by tridelat** [comment]
@zhang-alvin @cekees sounds good, and using the variableNames of the Coefficients class would be nice. One thing to think about is that some variableNames need to already know `nd` in order to be set with the right number of variables (e.g. https://github.com/erdc/proteus/blob/master/proteus/mprans/RANS2P.py#L379 ).
In practice this is not known until the TwoPhaseFlowProblem is "initialized" as it depends on its `domain` variable.

**Comment by tridelat** [comment]
@zhang-alvin do you have a backup of this? It is from a deleted repository ("unknown repository") right now

**Comment by zhang-alvin** [comment]
> @zhang-alvin do you have a backup of this? It is from a deleted repository ("unknown repository") right now

Yes I have a backup of this, I'll close this PR and reopen shortly.

**Comment by zhang-alvin** [comment]
See #1194 for continuation

**Pull request closed without merging**
