### PR TITLE
Add fct richards

### PR DESCRIPTION
**Pull request by cekees**
# Mandatory Checklist

Please ensure that the following criteria are met:

- [x] Title of pull request describes the changes/features
- [x] Request at least 2 reviewers
- [x] If new files are being added, the files are no larger than 100kB. Post the file sizes.
- [x] Code coverage did not decrease. If this is a bug fix, a test should cover that bug fix. If a new feature is added, a test should be made to cover that feature.
- [x] New features have appropriate documentation strings (readable by sphinx)
- [x] Contributor has read and agreed with CONTRIBUTING.md and has added themselves to CONTRIBUTORS.md 

As a general rule of thumb, try to follow [PEP8](https://www.python.org/dev/peps/pep-0008/) guidelines.

# Description

### CODE REVIEW

**Review by cekees — COMMENTED** [review]
Doubled checked all the changes...

**Comment by jhcollins** [comment]
I was hoping to run the richards tests. 
 If they pass on your machine then I will approve.

**Comment by cekees** [comment]
Yes, they run locally and in the Travis tests running on my fork. Thanks for reviewing!

**Comment by jhcollins** [comment]
On your fork, the air-water-vv was removed so will this make command fail? 
```makefile
test: air-water-vv check
```

**Review by jhcollins — APPROVED** [review]

**Comment by cekees** [comment]
Thanks, I will fix that in the makefile. I'm pushing the responsibility of testing air-water-vv and proteus_tutorial onto those repos so we can keep testing within limits of open source support in Travis.

**Pull request merged**
