### PR TITLE
SWFlow solver fixes.

### PR DESCRIPTION
**Pull request by ejtovar**
# Mandatory Checklist

Please ensure that the following criteria are met:

- [x] Title of pull request describes the changes/features
- [ ] Request at least 2 reviewers
- [x] If new files are being added, the files are no larger than 100kB. Post the file sizes.
- [ ] Code coverage did not decrease. If this is a bug fix, a test should cover that bug fix. If a new feature is added, a test should be made to cover that feature.
- [ ] New features have appropriate documentation strings (readable by sphinx)
- [x] Contributor has read and agreed with CONTRIBUTING.md and has added themselves to CONTRIBUTORS.md 

As a general rule of thumb, try to follow [PEP8](https://www.python.org/dev/peps/pep-0008/) guidelines.

# Description
Fixed some bugs in the SWFlow solvers.

### CODE REVIEW

**Comment by ejtovar** [comment]
@cekees The hashdist linux build is failing due to urllib being failed to download. Is this part of your changes in your latest PR?

**Comment by cekees** [comment]
> @cekees The hashdist linux build is failing due to urllib being failed to download. Is this part of your changes in your latest PR?

Yes, it will fix that. That PR is basically ready to go in, I'm just adjusting how we do coverage checking.

**Review by cekees — APPROVED** [review]
This looks great. I'm glad you're keeping both models updated. The only thing I'd like to do different is to got ahead and switch the data files over to git. If you've installed git-lfs and run `git lfs install` you could do something like the following:

1. Get the list of files that have changed git diff --name-status origin/main > files.sh
2.  Edit files.sh to remove the names of source files and leave only data files to go under LFS
3. Do `git rm --cached` for each file in there and then do `git commit` to remove them from  git
4. Do `git lfs track` and `git add -f` for each file, then `git commit`.
5. Do `git push` and `git lfs push` to push the data to lfs storage
6. verify on this PR that the data files now just show up as lfs pointers.
After they've been added to LFS like they shouldn't require any attention, just git add/commit them as usual and lfs will automatically handle the pointer information that lfs tracks.

**Comment by ejtovar** [comment]
I'll go ahead and do that. I will merge this after we merge your PR.

**Review by cekees — APPROVED** [review]
Looks great. I would do a squash and merge to clean up the history.

**Pull request merged**
